#!/usr/bin/env bash
#script that loops from 1->10 and:displays "bad luck" for the 4th iteration, "good luck" for 8th iteration and "Best School" for other iterations
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	x=$((x+1))
done
